# Generated by Django 3.2 on 2021-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_time', models.DateTimeField(null=True)),
                ('message_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Sub_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=20)),
                ('sub_starttime', models.DateTimeField(null=True)),
                ('sub_endtime', models.DateTimeField(null=True)),
            ],
        ),
    ]
